; =============================================================================
; os8088 - apps/catdemo/catdemo.asm
;
; CAT DEMO: a small demo package. One window, a drop-down (os88ui.inc's,
; SPEC.md 13.14) choosing one of five cats, and the cat drawn below it as
; vector line art. The lines are os88gfx.inc's app-side walk committed
; through OSAPI_GFX_POINTS (SPEC.md 5.12), so each stroke takes the pen
; colour it was given - the calico's patches are brown and black on a
; colour adapter, and stripes against solid fill on a 1bpp one.
;
; The pictures are data, not code: apps/catdemo/cats.inc, generated by
; apps/catdemo/mkcats.py (committed; the build does not run it). Each is a
; byte stream of colour changes and polylines in a 200 x 125 drawing space.
; =============================================================================

%include "os88api.inc"

    OS88_HEADER 'CATDEMO', ct_entry

CT_W      equ 214                   ; outer window size
CT_H      equ 172
CT_CONT_W equ CT_W - 2              ; content 212 x 153
CT_CONT_H equ CT_H - 19

CT_LBL_X  equ 6                     ; "Cat:" label, content-relative
CT_LBL_Y  equ 7
CT_DR_X   equ 42                    ; the drop-down's closed box
CT_DR_Y   equ 3
CT_DR_W   equ 126
CT_DR_H   equ 14
CT_PIC_X  equ 6                     ; the 200 x 125 drawing space
CT_PIC_Y  equ 24

CT_NPICS  equ 5
CT_PTMAX  equ 256                   ; points batched per OSAPI_GFX_POINTS

; -----------------------------------------------------------------------------
; ct_entry - package entry point (SPEC.md 20.2)
; in:  DS=ES=KERNEL_SEG... as every entry proc; gfx lock NOT held
; out: BX = window ptr, CF clear (CF set = abort)
; -----------------------------------------------------------------------------
ct_entry:
    push ax
    push si
    mov si, ct_tpl
    call OSAPI_WM_CREATE            ; BX = window ptr, CF on table full
    jc .out
    OS88_REGION_MOVABLE             ; no segment words point inside us
    mov [ct_drop + OS88UI_DR_WIN], bx
    mov ax, ct_ondrag
    call OSAPI_WM_ONDRAG            ; the drop-down's highlight follows
    mov ax, ct_onup
    call OSAPI_WM_ONMOUSEUP         ; ...and press-drag-release picks
    mov si, ct_about
    call OSAPI_ABOUT_SET
    clc
.out:
    pop si
    pop ax
    ret

; -----------------------------------------------------------------------------
; ct_paint - W_PAINT: label, picture, drop-down, About card (last, on top)
; in:  SI = window ptr; gfx lock held, content already white
; out: nothing; preserves all registers
; -----------------------------------------------------------------------------
ct_paint:
    push ax
    push bx
    push cx
    push dx
    push si
    push di
    mov bx, si
    call OSAPI_WM_CONTENT           ; AX = content left, DX = content top
    push si
    push ax
    push dx
    mov cx, ax
    add cx, CT_LBL_X
    add dx, CT_LBL_Y
    mov si, ct_s_lbl
    mov ax, (CWHITE << 8) | CBLACK
    call OSAPI_FONT_RUN
    pop dx
    pop ax
    add ax, CT_DR_X                 ; the drop-down's box, from where the
    add dx, CT_DR_Y                 ; window is NOW
    mov [ct_drop + 0], ax
    mov [ct_drop + 2], dx
    add ax, CT_DR_W - 1
    add dx, CT_DR_H - 1
    mov [ct_drop + 4], ax
    mov [ct_drop + 6], dx
    pop si
    call ct_draw                    ; the cat, under any open list
    mov bx, ct_drop
    xor di, di
    call os88ui_drop
    cmp byte [ct_abon], 0
    je .out
    mov bx, si
    mov si, ct_ablines
    call os88ui_about_d             ; _d: this paint's region is armed
.out:
    pop di
    pop si
    pop dx
    pop cx
    pop bx
    pop ax
    ret

; -----------------------------------------------------------------------------
; ct_draw - the selected cat, as polylines
; in:  SI = window ptr; gfx lock held, clip armed
; out: nothing; preserves all registers
; -----------------------------------------------------------------------------
ct_draw:
    push ax
    push bx
    push cx
    push dx
    push si
    push di
    push bp
    cld
    mov bx, si
    call OSAPI_WM_CONTENT
    add ax, CT_PIC_X
    mov [ct_ox], ax
    add dx, CT_PIC_Y
    mov [ct_oy], dx
    mov bx, [ct_drop + OS88UI_DR_SEL]
    shl bx, 1
    mov si, [ct_pics + bx]
    call gfxe_pnew
.rec:
    lodsb
    or al, al
    jz .done
    cmp al, 0FFh
    jne .poly
    push si                         ; a colour change: the batch so far goes
    call gfxe_pput                  ; out in the OLD ink first
    pop si
    lodsb
    call OSAPI_SET_COLOR
    jmp short .rec
.poly:
    xor ah, ah
    mov [ct_n], ax
    call ct_pt                      ; AX/BX = the first point
    dec word [ct_n]
    jz .rec
.seg:
    push ax
    push bx
    call ct_pt
    mov cx, ax                      ; CX/DX = this point, AX/BX = the last
    mov dx, bx
    pop bx
    pop ax
    push cx
    push dx
    push si
    mov di, ct_walk
    call gfxe_wline                 ; clobbers AX BX CX DX SI BP
    pop si
    pop bx                          ; this point is the next one's start
    pop ax
    dec word [ct_n]
    jnz .seg
    jmp short .rec
.done:
    call gfxe_pput
    pop bp
    pop di
    pop si
    pop dx
    pop cx
    pop bx
    pop ax
    ret

; ct_pt - read one x,y byte pair at SI into screen AX = x, BX = y; SI += 2
ct_pt:
    lodsb
    xor ah, ah
    add ax, [ct_ox]
    mov bx, ax
    lodsb
    xor ah, ah
    add ax, [ct_oy]
    xchg ax, bx
    ret

; -----------------------------------------------------------------------------
; ct_repaint - erase the content and draw it again
; in:  SI = window ptr; gfx lock held (a click or menu has no clip armed)
; out: nothing; preserves all registers
; -----------------------------------------------------------------------------
ct_repaint:
    push ax
    push bx
    push cx
    push dx
    mov bx, si
    call OSAPI_WM_CLIP_SET
    jc .out                         ; nothing of us is visible
    mov al, CWHITE
    call OSAPI_SET_COLOR
    call OSAPI_WM_CONTENT
    mov bx, dx
    mov cx, ax
    add cx, CT_CONT_W - 1
    add dx, CT_CONT_H - 1
    call OSAPI_GFX_FILL
    call ct_paint
.out:
    pop dx
    pop cx
    pop bx
    pop ax
    ret

; ct_answer - act on os88ui_drpress/os88ui_drup's AL/CF: a pick or a
;             list that could not put its own pixels back is a repaint
; in:  SI = window ptr, AL/CF the control's answer
ct_answer:
    jc .rep
    cmp al, 0FFh
    je .out
.rep:
    call ct_repaint
.out:
    ret

; -----------------------------------------------------------------------------
; ct_onclick / ct_ondrag / ct_onup - the drop-down's three mouse halves
; in:  CX = x, DX = y, SI = window ptr; gfx lock held
; out: nothing; preserves all registers
; -----------------------------------------------------------------------------
ct_onclick:
    push ax
    push bx
    call ct_abdismiss               ; a click takes the About card down first
    jc .out
    mov bx, ct_drop
    call os88ui_drpress
    call ct_answer
.out:
    pop bx
    pop ax
    ret

ct_ondrag:
    push bx
    mov bx, ct_drop
    call os88ui_drdrag
    pop bx
    ret

ct_onup:
    push ax
    push bx
    mov bx, ct_drop
    call os88ui_drup
    call ct_answer
    pop bx
    pop ax
    ret

; -----------------------------------------------------------------------------
; The standard About card (SPEC.md 12.2, 20.5.1) - hello.asm's pattern
; -----------------------------------------------------------------------------
ct_about:
    push bx
    push si
    mov bx, ct_drop                 ; an open list goes first
    call os88ui_drclose
    mov byte [ct_abon], 1
    pop si
    push si
    mov bx, si
    mov si, ct_ablines
    call os88ui_about
    pop si
    pop bx
    ret

; out: CF = 1 the card was up and the click was spent taking it down
ct_abdismiss:
    cmp byte [ct_abon], 0
    je .none
    mov byte [ct_abon], 0
    call ct_repaint
    stc
    ret
.none:
    clc
    ret

; --- window template (SPEC.md 11: 16 bytes, 8 words) ---------------------------
ct_tpl:
    dw 180, 40, CT_W, CT_H
    dw ct_ttl, ct_paint, 0, ct_onclick

; --- the drop-down's record (OS88UI_DR_SIZE bytes) ------------------------------
ct_drop:
    dw 0, 0, 0, 0                   ; the closed box, filled in by ct_paint
    dw ct_items, CT_NPICS, 0, 0     ; items, count, pick, window
    db 0, 0FFh                      ; open, hot
    dw 0, 0, 0, 0                   ; bank seg/KB, list top, disabled

ct_items:   dw ct_n0, ct_n1, ct_n2, ct_n3, ct_n4
ct_pics:    dw ct_pic0, ct_pic1, ct_pic2, ct_pic3, ct_pic4
ct_n0:      db 'Sitting Cat', 0
ct_n1:      db 'Sleeping Cat', 0
ct_n2:      db 'Calico Cat', 0
ct_n3:      db 'Walking Cat', 0
ct_n4:      db 'os8088 Mascot', 0

ct_ttl:     db 'Cat Demo', 0
ct_s_lbl:   db 'Cat:', 0

ct_ablines:
    dw ct_ab1, ct_ab2, ct_ab3, 0
ct_ab1:     db 'Cat Demo for os8088', 0
ct_ab2:     db 0
ct_ab3:     db 'Five cats in vector art', 0

%include "cats.inc"

; --- the shared libraries (at the end of the code, before OS88_BSS) -------------
%define OS88UI_ABOUT
%define OS88UI_DROP
%define OS88UI_NOGLYPH
%include "os88ui.inc"

%define GFXE_WALK
%define GFXE_PT_BUF ct_ptbuf
%define GFXE_PT_MAX CT_PTMAX
%include "os88gfx.inc"

    OS88_BSS 24 + CT_PTMAX * 4
    OS88_IMAGE_END

; --- loader-zeroed bss -------------------------------------------------------
ct_abon     equ os88_image_end + 0   ; byte: the About card is up
ct_ox       equ os88_image_end + 2   ; word: picture origin, screen x
ct_oy       equ os88_image_end + 4   ; word: ...and y
ct_n        equ os88_image_end + 6   ; word: points left in this polyline
ct_walk     equ os88_image_end + 8   ; 14 bytes: os88gfx.inc's walk block
ct_ptbuf    equ os88_image_end + 24  ; CT_PTMAX * 4: the point batch
